version: '3.4'

services:
  app:
    build: .
    env_file: ./dev.env
    depends_on:
      - postgres
    restart: always
    expose:
      - 4444
    ports:
      - 4444:4444
    volumes:
      - .:/app/
    command: npm run start
    networks:
      - spacex_network

  postgres:
    image: postgres:12
    env_file: ./db.env
    ports:
      - 5432:5432
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
    restart: always
    networks:
      - spacex_network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:4.18
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 8080:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - spacex_network

volumes:
  pgadmin_data:

networks:
  spacex_network:
    driver: bridge
