const REQUEST = '_REQUEST';
const SUCCESS = '_SUCCESS';
const FAILURE = '_FAILURE';

const SIGN_IN = 'SIGN_IN';
const SIGN_UP = 'SIGN_UP';
const LOG_OUT = 'LOG_OUT';
const GET_USER_DATA = 'GET_USER_DATA';
const CHANGE_USER_DATA = 'CHANGE_USER_DATA';
const CHANGE_USER_PASSWORD = 'CHANGE_USER_PASSWORD';
const CHANGE_USER_AVATAR = 'CHANGE_USER_AVATAR';
const PUT_GAME_LEADER_DATA = 'PUT_GAME_LEADER_DATA';

export const SIGN_IN_REQUEST = `${SIGN_IN}${REQUEST}`;
export const SIGN_IN_SUCCESS = `${SIGN_IN}${SUCCESS}`;
export const SIGN_IN_FAILURE = `${SIGN_IN}${FAILURE}`;
export const GAME_OVER_MODAL_TOGGLE = `GAME_OVER_MODAL_TOGGLE`;
export const TOGGLE_GAME_MODAL = `TOGGLE_GAME_MODAL`;

export const SIGN_UP_REQUEST = `${SIGN_UP}${REQUEST}`;
export const SIGN_UP_SUCCESS = `${SIGN_UP}${SUCCESS}`;
export const SIGN_UP_FAILURE = `${SIGN_UP}${FAILURE}`;

export const LOG_OUT_REQUEST = `${LOG_OUT}${REQUEST}`;
export const LOG_OUT_SUCCESS = `${LOG_OUT}${SUCCESS}`;
export const LOG_OUT_FAILURE = `${LOG_OUT}${FAILURE}`;

export const GET_USER_DATA_REQUEST = `${GET_USER_DATA}${REQUEST}`;
export const GET_USER_DATA_SUCCESS = `${GET_USER_DATA}${SUCCESS}`;
export const GET_USER_DATA_FAILURE = `${GET_USER_DATA}${FAILURE}`;

export const CHANGE_USER_DATA_REQUEST = `${CHANGE_USER_DATA}${REQUEST}`;
export const CHANGE_USER_DATA_SUCCESS = `${CHANGE_USER_DATA}${SUCCESS}`;
export const CHANGE_USER_DATA_FAILURE = `${CHANGE_USER_DATA}${FAILURE}`;

export const CHANGE_USER_PASSWORD_REQUEST = `${CHANGE_USER_PASSWORD}${REQUEST}`;
export const CHANGE_USER_PASSWORD_SUCCESS = `${CHANGE_USER_PASSWORD}${SUCCESS}`;
export const CHANGE_USER_PASSWORD_FAILURE = `${CHANGE_USER_PASSWORD}${FAILURE}`;

export const CHANGE_USER_AVATAR_REQUEST = `${CHANGE_USER_AVATAR}${REQUEST}`;
export const CHANGE_USER_AVATAR_SUCCESS = `${CHANGE_USER_AVATAR}${SUCCESS}`;
export const CHANGE_USER_AVATAR_FAILURE = `${CHANGE_USER_AVATAR}${FAILURE}`;

export const PUT_GAME_LEADER_DATA_REQUEST = `${PUT_GAME_LEADER_DATA}${REQUEST}`;
export const PUT_GAME_LEADER_DATA_SUCCESS = `${PUT_GAME_LEADER_DATA}${SUCCESS}`;
export const PUT_GAME_LEADER_DATA_FAILURE = `${PUT_GAME_LEADER_DATA}${FAILURE}`;

export const INCREASE_GAME_SCORE = `INCREASE_GAME_SCORE`;
export const REDUCE_GAME_LIVES = `REDUCE_GAME_LIVES`;
export const RESTART_GAME = `RESTART_GAME`;
