const REQUEST = '_REQUEST';
const SUCCESS = '_SUCCESS';
const FAILURE = '_FAILURE';

const SIGN_IN = 'SIGN_IN';
const SIGN_UP = 'SIGN_UP';
const LOG_OUT = 'LOG_OUT';
const GET_USER_DATA = 'GET_USER_DATA';

const CHANGE_USER_DATA = 'CHANGE_USER_DATA';
const CHANGE_USER_THEME = 'CHANGE_USER_THEME';
const CHANGE_USER_PASSWORD = 'CHANGE_USER_PASSWORD';
const CHANGE_USER_AVATAR = 'CHANGE_USER_AVATAR';
const PUT_GAME_LEADER_DATA = 'PUT_GAME_LEADER_DATA';
const GET_GAME_LEADER_DATA = 'GET_GAME_LEADER_DATA';
const CREATE_FEEDBACK = 'CREATE_FEEDBACK';
export const RESET_FEEDBACK = 'RESET_FEEDBACK';
const GET_FORUM_TOPICS = 'GET_FORUM_TOPICS';
const CREATE_FORUM_TOPIC = 'CREATE_FORUM_TOPIC';
const GET_FORUM_TOPIC_POSTS = 'GET_FORUM_TOPIC_POSTS';
const CREATE_FORUM_TOPIC_POST = 'CREATE_FORUM_TOPIC_POST';

export const SIGN_IN_REQUEST = `${SIGN_IN}${REQUEST}`;
export const SIGN_IN_SUCCESS = `${SIGN_IN}${SUCCESS}`;
export const SIGN_IN_FAILURE = `${SIGN_IN}${FAILURE}`;
export const GAME_OVER_MODAL_TOGGLE = `GAME_OVER_MODAL_TOGGLE`;
export const TOGGLE_GAME_MODAL = `TOGGLE_GAME_MODAL`;

export const SIGN_UP_REQUEST = `${SIGN_UP}${REQUEST}`;
export const SIGN_UP_SUCCESS = `${SIGN_UP}${SUCCESS}`;
export const SIGN_UP_FAILURE = `${SIGN_UP}${FAILURE}`;

export const LOG_OUT_REQUEST = `${LOG_OUT}${REQUEST}`;
export const LOG_OUT_SUCCESS = `${LOG_OUT}${SUCCESS}`;
export const LOG_OUT_FAILURE = `${LOG_OUT}${FAILURE}`;

export const GET_USER_DATA_REQUEST = `${GET_USER_DATA}${REQUEST}`;
export const GET_USER_DATA_SUCCESS = `${GET_USER_DATA}${SUCCESS}`;
export const GET_USER_DATA_FAILURE = `${GET_USER_DATA}${FAILURE}`;

export const CHANGE_USER_DATA_REQUEST = `${CHANGE_USER_DATA}${REQUEST}`;
export const CHANGE_USER_DATA_SUCCESS = `${CHANGE_USER_DATA}${SUCCESS}`;
export const CHANGE_USER_DATA_FAILURE = `${CHANGE_USER_DATA}${FAILURE}`;

export const CHANGE_USER_THEME_REQUEST = `${CHANGE_USER_THEME}${REQUEST}`;
export const CHANGE_USER_THEME_SUCCESS = `${CHANGE_USER_THEME}${SUCCESS}`;
export const CHANGE_USER_THEME_FAILURE = `${CHANGE_USER_THEME}${FAILURE}`;

export const CHANGE_USER_PASSWORD_REQUEST = `${CHANGE_USER_PASSWORD}${REQUEST}`;
export const CHANGE_USER_PASSWORD_SUCCESS = `${CHANGE_USER_PASSWORD}${SUCCESS}`;
export const CHANGE_USER_PASSWORD_FAILURE = `${CHANGE_USER_PASSWORD}${FAILURE}`;

export const CREATE_FEEDBACK_REQUEST = `${CREATE_FEEDBACK}${REQUEST}`;
export const CREATE_FEEDBACK_SUCCESS = `${CREATE_FEEDBACK}${SUCCESS}`;
export const CREATE_FEEDBACK_FAILURE = `${CREATE_FEEDBACK}${FAILURE}`;

export const CHANGE_USER_AVATAR_REQUEST = `${CHANGE_USER_AVATAR}${REQUEST}`;
export const CHANGE_USER_AVATAR_SUCCESS = `${CHANGE_USER_AVATAR}${SUCCESS}`;
export const CHANGE_USER_AVATAR_FAILURE = `${CHANGE_USER_AVATAR}${FAILURE}`;

export const CREATE_FORUM_TOPIC_REQUEST = `${CREATE_FORUM_TOPIC}${REQUEST}`;
export const CREATE_FORUM_TOPIC_SUCCESS = `${CREATE_FORUM_TOPIC}${SUCCESS}`;

export const GET_FORUM_TOPICS_REQUEST = `${GET_FORUM_TOPICS}${REQUEST}`;
export const GET_FORUM_TOPICS_SUCCESS = `${GET_FORUM_TOPICS}${SUCCESS}`;
export const GET_FORUM_TOPICS_FAILURE = `${GET_FORUM_TOPICS}${FAILURE}`;

export const CREATE_FORUM_TOPIC_POST_REQUEST = `${CREATE_FORUM_TOPIC_POST}${REQUEST}`;
export const CREATE_FORUM_TOPIC_POST_SUCCESS = `${CREATE_FORUM_TOPIC_POST}${SUCCESS}`;

export const GET_FORUM_TOPIC_POSTS_REQUEST = `${GET_FORUM_TOPIC_POSTS}${REQUEST}`;
export const GET_FORUM_TOPIC_POSTS_SUCCESS = `${GET_FORUM_TOPIC_POSTS}${SUCCESS}`;

export const PUT_GAME_LEADER_DATA_REQUEST = `${PUT_GAME_LEADER_DATA}${REQUEST}`;
export const PUT_GAME_LEADER_DATA_FAILURE = `${PUT_GAME_LEADER_DATA}${FAILURE}`;

export const GET_GAME_LEADER_DATA_REQUEST = `${GET_GAME_LEADER_DATA}${REQUEST}`;
export const GET_GAME_LEADER_DATA_SUCCESS = `${GET_GAME_LEADER_DATA}${SUCCESS}`;
export const GET_GAME_LEADER_DATA_FAILURE = `${GET_GAME_LEADER_DATA}${FAILURE}`;

export const INCREASE_GAME_SCORE = `INCREASE_GAME_SCORE`;
export const REDUCE_GAME_LIVES = `REDUCE_GAME_LIVES`;
export const RESTART_GAME = `RESTART_GAME`;

export const FULLSCREEN_ON = `FULLSCREEN_ON`;
export const FULLSCREEN_OFF = `FULLSCREEN_OFF`;
