name: deploy to nairobi-arcnd-4.ya-praktikum.tech
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: deploy to YC
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            cd /spacex
            git checkout dev
            git pull
            docker-compose build
            docker-compose up -d
          host: 84.252.130.70
          username: oleg
          passphrase: ${{ secrets.PASSPHRASE }}
          privateKey: ${{ secrets.PRIVATE_KEY}}
